version: '3.8'

services:
  king-16:
    image: david-16
    build: .
    ports:
      - '7000:7000'
    environment:
      - MONGODB_URI:'mongodb://localhost:27017/trail'
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
